# -*- coding: utf-8 -*-
"""CVLAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgErM1E1ODVXfkFgNhdSNBaQfDjJHtKU
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

def show_image(title,img,cmap=None):
    plt.figure(figsize=(5,5))
    plt.title(title)
    if cmap:
      plt.imshow(img,cmap=cmap)
    else:
      plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

img1=cv2.imread("/content/drive/MyDrive/Colab Notebooks/nature1.jpg")
img2=cv2.imread("/content/drive/MyDrive/Colab Notebooks/nature2.jpg")

show_image("MOUNTAINS",img1)
show_image("RIVER",img2)

print(img1.shape)
print(img2.shape)

img2=cv2.resize(img2,(img1.shape[1],img1.shape[0]))

cropped_img = img1[50:800, 100:700]
show_image("Cropped Image", cropped_img)

added_img=cv2.addWeighted(img1,0.5,img2,0.5,0)
show_image("Arthematic Addition(Blending)",added_img)

subtracted_img=cv2.subtract(img1,img2)
show_image("Arthematic Subtraction",subtracted_img)

rectangle=np.zeros((img1.shape[0],img1.shape[1]),dtype="uint8")
cv2.rectangle(rectangle,(50,50),(300,300),255,-1)
show_image("Rectangle",rectangle)

circle=np.zeros((img1.shape[0],img1.shape[1]),dtype="uint8")
cv2.circle(circle,(300,300),300,255,-1)
show_image("Circle",circle)

bitwise_and=cv2.bitwise_and(rectangle,circle)
show_image("Bitwise AND",bitwise_and,cmap='gray')

bitwise_or=cv2.bitwise_or(rectangle,circle)
show_image("Bitwise OR",bitwise_or,cmap='gray')

bitwise_xor=cv2.bitwise_xor(rectangle,circle)
show_image("Bitwise XOR",bitwise_xor,cmap='gray')

bitwise_not=cv2.bitwise_not(rectangle,circle)
show_image("Bitwise NOT",bitwise_not,cmap='gray')

def rotation_func(angle_in_radians):
    return np.array([
        [np.cos(angle_in_radians), np.sin(angle_in_radians)],
        [-np.sin(angle_in_radians), np.cos(angle_in_radians)]
    ])

gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)

show_image("Gray Image", gray, cmap="gray")

m, n = gray.shape

rotation_matrix = rotation_func(np.pi / 2)

rotated_image = np.zeros((m, n), dtype=gray.dtype)

for i in range(m):
    for j in range(n):

        x = i - m // 2
        y = j - n // 2

        a, b = rotation_matrix @ np.array([x, y])

        a = int(round(a))
        b = int(round(b))

        if (0 <= a + m // 2 < m) and (0 <= b + n // 2 < n):
            rotated_image[a + m // 2, b + n // 2] = gray[i, j]

show_image("Rotated Image", rotated_image, cmap="gray")

(h, w) = img1.shape[:2]

center = (w // 2, h // 2)

M = cv2.getRotationMatrix2D(center, 90, 1)

rotated = cv2.warpAffine(img1, M, (w, h))

show_image("OpenCV Rotated Image", rotated)